2018-10-16 18:55:54	Client initialized
2018-10-16 18:55:56	Message: <2|asd,asd,18475> sended to the server correctly
2018-10-16 18:55:56	Received a message from the SERVER: ?|1
2018-10-16 18:55:56	Succesfull logged in as asd
2018-10-16 18:55:56	Received a message from the SERVER: 0
2018-10-16 18:55:56	No messages stored in the server
2018-10-16 18:55:56	MessageHandler Initialized! Associated port: 18475
2018-10-16 18:55:58	Message: <3|assd> sended to the server correctly
2018-10-16 18:55:58	Received a message from the SERVER: !|-3
2018-10-16 18:55:58	Error: the contacted user does not exist
2018-10-16 18:55:59	Message: <3|assd> sended to the server correctly
2018-10-16 18:55:59	Received a message from the SERVER: !|-3
2018-10-16 18:55:59	Error: the contacted user does not exist
2018-10-16 18:55:59	Message: <3|assd> sended to the server correctly
2018-10-16 18:55:59	Received a message from the SERVER: !|-3
2018-10-16 18:55:59	Error: the contacted user does not exist
2018-10-16 18:55:59	Message: <3|assd> sended to the server correctly
2018-10-16 18:55:59	Received a message from the SERVER: !|-3
2018-10-16 18:55:59	Error: the contacted user does not exist
2018-10-16 18:55:59	Message: <3|assd> sended to the server correctly
2018-10-16 18:55:59	Received a message from the SERVER: !|-3
2018-10-16 18:55:59	Error: the contacted user does not exist
2018-10-16 18:56:01	Message: <3|Prova> sended to the server correctly
2018-10-16 18:56:01	Received a message from the SERVER: !|0
2018-10-16 18:56:01	user offline
2018-10-16 18:56:05	Message: <3|PY_VAR0> sended to the server correctly
2018-10-16 18:56:05	Received a message from the SERVER: !|-3
2018-10-16 18:56:05	Error: the contacted user does not exist
